### ISSUE TITLE
Video resolution parametrization

### ISSUE THREAD

**Issue by GregBaggings** [sudharsan-selvaraj/appium-dashboard-plugin#119]
Is there any way to specify the resolution of the created video?
If not, could you please include some future configuration option for that?

The size of the videos should be seriously considered and optimized because in CI/CD systems, these videos can take a huge space.

Anyway, great job so far, keep it up! :)

**Comment by ZGrauer** [comment]
This might also solve the issue where ffmpeg doesn't start recording due to this issue with a device's resolution.

```shell
2023-03-01 14:02:28:732 - [ffmpeg] [libx264 @ 0x7fda5f005280] width not divisible by 2 (1125x2436)
```

If we could set the video scale, then we could solve this issue and get videos to record.  Right now I have to add `videoScale` to the options when starting video recording.

`appium-dashboard/lib/plugin/driver-command-executor.js`
```javascript
        options: {
          videoType: "libx264",
          videoFps: 10,
          videoScale: "1280:720",
          /* In android, adb can record only 3 mins of video. below timeLimit is used to take longer video */
          timeLimit: 1800, //in seconds (30 min)
        },
```

**Comment by ZGrauer** [comment]
@GregBaggings this feature has been added to v2.0.2.  Add capability `dashboard:videoResolution` to your test with the value `widthxheight`, like `1920x1080`

**Comment by GregBaggings** [comment]
Wonderful! Thank you @ZGrauer!
